const PROPERTY_IMAGE_PROTOCOLS_BY_HOST = new Map<string, ReadonlySet<string>>([
  ["123immo.es", new Set(["https:"])],
  ["agencymgam.com", new Set(["https:"])],
  ["api.bennecke.com", new Set(["https:"])],
  ["appropertiesspain.com", new Set(["https:"])],
  ["assetsrv.advanceagent.co.uk", new Set(["https:"])],
  ["bb1.vendomia-cdn.com", new Set(["https:"])],
  ["bel-chic.com", new Set(["https:"])],
  ["casa-solyanza.com", new Set(["https:"])],
  ["casas-connect.es", new Set(["https:"])],
  ["casaspanishhomes.com", new Set(["https:"])],
  ["casaswilson.com", new Set(["https:"])],
  ["cjrealestate.eu", new Set(["https:"])],
  ["cweflengroup.com", new Set(["https:"])],
  ["datasources.medlandspain.net", new Set(["https:"])],
  ["dolphin-properties.com", new Set(["https:"])],
  ["ds-realestate.com", new Set(["https:"])],
  ["estbd.io", new Set(["https:"])],
  ["europeangli.inmoenter.com", new Set(["https:"])],
  ["feedmedia.egorealestate.com", new Set(["https:"])],
  ["fotos15.apinmo.com", new Set(["https:"])],
  ["frontlinepropertiesspain.com", new Set(["https:"])],
  ["global-spain.com", new Set(["https:"])],
  ["gsmakelaars.com", new Set(["https:"])],
  ["houseinspaininvest.com", new Set(["https:"])],
  ["images.optima-crm.com", new Set(["https:"])],
  ["immoalicante.com", new Set(["https:"])],
  ["immoleromino.com", new Set(["https:"])],
  ["immomurcialicante.com", new Set(["https:"])],
  ["inmoifach.inmoenter.com", new Set(["https:"])],
  ["insunproperties.com", new Set(["https:"])],
  ["investforhome.com", new Set(["https:"])],
  ["larrosaandco.com", new Set(["https:"])],
  ["lehomes.es", new Set(["https:"])],
  ["media-feed-v2.resales-online.com", new Set(["https:"])],
  ["media-feed.resales-online.com", new Set(["https:"])],
  ["members.alphashare.com", new Set(["https:"])],
  ["mgp.properties", new Set(["https:"])],
  ["micosta.be", new Set(["https:"])],
  ["movr.es", new Set(["https:"])],
  ["oldsite.wow-estates.com", new Set(["https:"])],
  ["palmhouses.es", new Set(["https:"])],
  ["premierproperties.es", new Set(["https:"])],
  ["realestatebykathy.es", new Set(["https:"])],
  ["redpalmestate.com", new Set(["https:"])],
  ["res.cloudinary.com", new Set(["https:"])],
  [
    "respacio-4c53102df1c9de6eca4f00689a84fb6b.s3.eu-west-3.amazonaws.com",
    new Set(["https:"]),
  ],
  ["s-homes.es", new Set(["https:"])],
  ["sanluises.com", new Set(["https:"])],
  ["smileproperties.es", new Set(["https:"])],
  ["spanishhomeslink.com", new Set(["https:"])],
  ["sunnierhomes.com", new Set(["https:"])],
  ["sunsealife.com", new Set(["https:"])],
  ["torrevieja-immo.com", new Set(["https:"])],
  ["ulrichbrack.com", new Set(["https:"])],
  ["www.1casa.com", new Set(["https:"])],
  ["www.andalusianhouse.com", new Set(["http:", "https:"])],
  ["www.costablancajaveaproperties.es", new Set(["https:"])],
  ["www.easyinmo.net", new Set(["https:"])],
  ["www.espanadreamproperties.com", new Set(["https:"])],
  ["www.homes-abroad.com", new Set(["https:"])],
  ["www.hotpropertiesinspain.com", new Set(["http:", "https:"])],
  ["www.immomoment-costablanca.com", new Set(["https:"])],
  ["www.inmoserver.com", new Set(["https:"])],
  ["www.keystonepropertyspain.com", new Set(["https:"])],
  ["www.marazulproperties.com", new Set(["https:"])],
  ["www.medvillaspanje.com", new Set(["https:"])],
  ["www.nemovitostivespanelsku.com", new Set(["https:"])],
  ["www.platinumpropertyspain.com", new Set(["https:"])],
  ["www.propmls.com", new Set(["https:"])],
  ["www.props.es", new Set(["https:"])],
  ["www.robertoproperties.com", new Set(["https:"])],
  ["www.s-villas.com", new Set(["https:"])],
  ["www.smartsell.es", new Set(["https:"])],
  ["www.stratusinternational.com", new Set(["https:"])],
  ["www.sunlandspain.com", new Set(["https:"])],
  ["www.thepropertyteam.es", new Set(["https:"])],
  ["www.vandamestates.com", new Set(["https:"])],
  ["www.villaquest.co.uk", new Set(["https:"])],
  ["www.viviendanet.com", new Set(["https:"])],
  ["www.welcome-estates.com", new Set(["https:"])],
]);

export function isAllowedPropertyImageUrl(url: URL): boolean {
  if (url.username || url.password || url.port) return false;

  const allowedProtocols = PROPERTY_IMAGE_PROTOCOLS_BY_HOST.get(
    url.hostname.toLowerCase(),
  );

  return allowedProtocols?.has(url.protocol) ?? false;
}
